<html lang="pt-br">

<head>
    <link rel="stylesheet" href="style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik+Wet+Paint&display=swap" rel="stylesheet">
    <title>Aluraflix</title>
</head>

<body>
    <section>
        <header>
SarahFLIX</header>
        <div class="chamada-texto">
            <h1>ATRAVÉS DO ARANHAVERSO </h1>
            <p>#homem-aranha</p>
        </div>

        <div>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/gt_fAE1Eg2Q?si=8swwGBTc-e9zveQ_"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
    </section>


    <section>
        <h2>filmes e séries</h2>
        <div class="categoria-videos">
            
            <a href="https://www.youtube.com/watch?v=cs15QqG6Gjc">
                <img src="https://img.youtube.com/vi/cs15QqG6Gjc/maxresdefault.jpg" />
            </a>
            <a href="https://www.youtube.com/watch?v=nCmIwcycUJ8">
                <img src="https://img.youtube.com/vi/nCmIwcycUJ8/maxresdefault.jpg" />
                
            </a>
            <a href="https://www.youtube.com/watch?v=TBWqm5xKVfI">
                <img src="https://img.youtube.com/vi/TBWqm5xKVfI/maxresdefault.jpg" />
            </a>
            <a href="https://www.youtube.com/watch?v=nkxaxyPya1o">
                <img src="https://img.youtube.com/vi/nkxaxyPya1o/maxresdefault.jpg" />
            </a>
            <a href="https://www.youtube.com/watch?v=SPht5SpOsts">
                <img src="https://img.youtube.com/vi/SPht5SpOsts/maxresdefault.jpg" />
            </a>
    
        </div>
    </section>









body{
    color:white;
    background:purple;
    margin:0px;
    font-family: "Rubik Wet Paint", system-ui;
    margin-bottom:100px;
body {
    color: white;
    background: black;
    margin: 0px;
    font-family: "Chakra Petch", sans-serif;
    margin-bottom: 100px;
}

header{
    border-bottom: solid 2px rgb(42,122,228);
    padding:20px;
    font-size:30px;
    color:rgb(42,122,228)
    
header {
    border-bottom: solid 2px rgb(42, 122, 228);
    padding: 20px;
    font-size: 32px;
    color: rgb(42, 122, 228);
}

.chamada{
    background:rgb(138,43,226);
    padding-bottom:80px; 
    padding-top:80px;
    display:flex;
    justify-content:center;
.chamada {
    background: rgb(184, 156, 213);
    padding-bottom: 80px;
    padding-top: 80px;
    display: flex;
    justify-content: center;
}

.chamada-texto{
    margin-right:5%;
.chamada-texto {
    margin-right: 5%;
}

h1{
    font-size:40px
h1 {
    font-size: 40px;
}

p{
    font-size:30px
}
img{
    height:200px
p {
    font-size: 20px;
}

.categoria-videos{
    display:flex;
    overflow-x:auto;
    gap:15px
.categoria-videos {
    display: flex;
    overflow-x: auto;
    gap: 10px;
}

.categoria{
    padding-left:20px;
.categoria {
    padding-left: 20px;
    padding-right: 20px;
    margin-top:50px;
    margin-top: 50px;
}

.categoria-videos img { 
    opacity:0.6;
    height:200px;
.categoria-videos img {
    opacity: 0.5;
    height: 200px;
}

.categoria-videos img:hover{
opacity:1.0;
border:1px solid blue
.categoria-videos img:hover {
    opacity: 1.0;
    border: 3px solid green;
}

.categoria h2 {
    color:rgb(42,122,228);
}
    color: rgb(42, 122, 228);
}
